# Production Environment Configuration
# Optimized for high availability, performance, and security

defaults:
  - base
  - override /model: musicgen_large
  - override /infrastructure: kubernetes

# @package _global_
app:
  environment: "production"
  debug: false

# Production API Settings
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4  # Multiple workers for high concurrency
  reload: false
  debug: false
  cors:
    enabled: true
    origins: 
      - "https://musicgen-ai.com"
      - "https://api.musicgen-ai.com"
      - "https://app.musicgen-ai.com"
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    headers: ["Authorization", "Content-Type", "Accept", "X-API-Key"]
    credentials: true
    max_age: 86400  # 24 hours

# Maximum Security for Production
auth:
  enabled: true
  jwt_secret: "${JWT_SECRET}"  # Must be set securely
  jwt_algorithm: "RS256"  # More secure algorithm
  jwt_expiration_hours: 8
  api_key_required: true
  allowed_api_keys: []  # Loaded from secure storage
  rate_limiting:
    enabled: true
    requests_per_minute: 30  # Conservative limit
    burst_limit: 5
    per_user_limit: 100

# High-Performance Model Settings
model:
  default_model: "facebook/musicgen-large"
  cache_size: 6  # Larger cache for performance
  device: "auto"  # Prefer GPU
  mixed_precision: true
  compile_model: true
  download_timeout_seconds: 180
  preload_models: ["facebook/musicgen-medium", "facebook/musicgen-large"]

# Production Generation Settings
generation:
  default_duration: 10.0
  max_duration: 60.0
  default_temperature: 0.8
  max_batch_size: 2  # Conservative for stability
  timeout_seconds: 120
  quality_mode: "high"
  priority_queue_enabled: true

# Production Audio Settings
audio:
  sample_rate: 24000
  format: "wav"
  output_dir: "/app/outputs/audio"
  temp_dir: "/tmp/audio"
  cleanup_temp_files: true
  backup_outputs: true
  backup_retention_days: 7

# Optimized Resource Management
resources:
  max_memory_usage_percent: 75.0  # Conservative limits
  max_cpu_usage_percent: 80.0
  cleanup_threshold_percent: 70.0
  monitoring_interval_seconds: 60.0
  auto_cleanup_enabled: true
  gpu_memory_fraction: 0.8
  memory_pressure_handling: "aggressive"

# Production Data Settings
data:
  datasets_dir: "/app/data/datasets"
  cache_dir: "/app/cache/data"
  preprocessing:
    num_workers: 6
    batch_size: 32
    persistent_workers: true

# Comprehensive Production Monitoring
monitoring:
  enabled: true
  metrics:
    enabled: true
    port: 9090
    endpoint: "/metrics"
    detailed_metrics: true
    custom_metrics: true
  health_check:
    enabled: true
    endpoint: "/health"
    detailed_endpoint: "/health/detailed"
    liveness_probe: "/health/live"
    readiness_probe: "/health/ready"
  logging:
    level: "WARN"  # Reduce log noise
    format: "json"
    file_rotation: true
    max_file_size_mb: 100
    backup_count: 30
    console_output: false
    structured_logging: true
    correlation_id: true

# Production Features (Stable Only)
features:
  streaming_generation: true
  multi_instrument: false  # Disable until fully tested
  batch_processing: true
  conditioning: true
  model_switching: true
  audio_effects: false  # Disable experimental features
  midi_export: false

# Production Tools (Minimal)
dev_tools:
  profiling_enabled: false
  debug_sql: false
  mock_slow_operations: false
  test_mode: false
  hot_reload: false

# Strict Production Validation
validation:
  strict_mode: true
  validate_audio_output: true
  validate_model_outputs: true
  max_prompt_length: 800  # Conservative limit
  min_duration: 1.0
  max_file_size_mb: 50

# Production External Services
external_services:
  wandb:
    enabled: true
    project: "musicgen-ai-production"
    entity: "${WANDB_ENTITY}"
    api_key: "${WANDB_API_KEY}"
    log_frequency: "minimal"
  
  redis:
    enabled: true
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT:6379}"
    db: 0
    password: "${REDIS_PASSWORD}"
    ssl: true
    ssl_verify: true
    connection_pool_size: 20
    max_connections: 100
    health_check_interval: 30
  
  postgresql:
    enabled: true
    host: "${POSTGRES_HOST}"
    port: "${POSTGRES_PORT:5432}"
    database: "${POSTGRES_DB:musicgen_prod}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    ssl_mode: "require"
    pool_size: 20
    max_overflow: 50
    pool_timeout: 30
    health_check_interval: 60

# Production-Specific Settings
production:
  high_availability:
    enabled: true
    health_checks: true
    graceful_shutdown_timeout: 30
    circuit_breaker: true
    retry_policy:
      max_retries: 3
      backoff_factor: 2
      max_delay: 60
  
  performance:
    connection_pooling: true
    caching_strategy: "aggressive"
    preload_critical_data: true
    optimize_for_latency: true
  
  security:
    request_validation: "strict"
    response_sanitization: true
    security_headers: true
    audit_logging: true
    ip_whitelisting: false  # Configure separately
    ddos_protection: true
  
  monitoring:
    apm_enabled: true
    error_tracking: true
    performance_monitoring: true
    uptime_monitoring: true
    alerting:
      enabled: true
      channels: ["email", "slack", "pagerduty"]
      escalation_policy: true
  
  backup:
    enabled: true
    frequency: "daily"
    retention_days: 90
    encryption: true
    offsite_backup: true

# Resource Limits and Quotas
limits:
  max_requests_per_hour: 1000
  max_generation_time_minutes: 5
  max_concurrent_generations: 10
  max_queue_size: 100
  max_user_storage_mb: 1000