version: '3.8'

services:
  # Pre-built MusicGen container
  musicgen-production:
    image: ashleykza/tts-webui:latest
    container_name: musicgen-production
    restart: unless-stopped
    volumes:
      - /Users/brightliu/Coding_Projects/music_gen/workspace:/workspace
      - /Users/brightliu/Coding_Projects/music_gen/outputs:/outputs
      - /Users/brightliu/Coding_Projects/music_gen/models:/models
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=3001
    networks:
      - musicgen-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # API Bridge
  musicgen-api-bridge:
    image: python:3.11-slim
    container_name: musicgen-api-bridge
    restart: unless-stopped
    volumes:
      - /Users/brightliu/Coding_Projects/music_gen/configs/api_bridge.py:/app/api_bridge.py
      - /Users/brightliu/Coding_Projects/music_gen/outputs:/outputs
    working_dir: /app
    command: |
      sh -c "pip install fastapi uvicorn httpx && python api_bridge.py"
    environment:
      - TTS_SERVICE_URL=http://musicgen-production:3001
    networks:
      - musicgen-net
    depends_on:
      - musicgen-production

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: musicgen-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /Users/brightliu/Coding_Projects/music_gen/configs/nginx-production.conf:/etc/nginx/nginx.conf:ro
      - /Users/brightliu/Coding_Projects/music_gen/outputs:/outputs:ro
    networks:
      - musicgen-net
    depends_on:
      - musicgen-api-bridge

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: musicgen-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /Users/brightliu/Coding_Projects/music_gen/configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - musicgen-net

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: musicgen-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=musicgen2024
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - musicgen-net
    depends_on:
      - prometheus

networks:
  musicgen-net:
    driver: bridge

volumes:
  grafana-storage:
