name: music-gen-ai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - scipy>=1.9.0
  
  # PyTorch ecosystem
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  
  # Audio processing
  - librosa>=0.10.0
  - soundfile>=0.12.0
  - ffmpeg
  
  # Scientific computing
  - scikit-learn>=1.2.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - pandas>=1.5.0
  
  # Development tools
  - jupyter
  - ipywidgets
  - nodejs>=16.0.0
  
  # System dependencies
  - git
  - curl
  - wget
  
  # Pip dependencies (not available in conda)
  - pip:
    - pytorch-lightning>=2.0.0
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0
    - transformers>=4.30.0
    - encodec>=0.1.1
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.22.0
    - wandb>=0.15.0
    - pretty-midi>=0.2.9
    - pydantic>=2.0.0
    - python-multipart>=0.0.6
    - aiofiles>=23.0.0
    - rich>=13.0.0
    - typer>=0.9.0
    - pytest>=7.0.0
    - pytest-asyncio>=0.21.0
    - pytest-cov>=4.0.0
    - black>=23.0.0
    - isort>=5.12.0
    - flake8>=6.0.0
    - mypy>=1.0.0
    - pre-commit>=3.0.0
    - tensorboard>=2.13.0
    - gunicorn>=20.0.0
    - prometheus-client>=0.16.0
    - opentelemetry-api>=1.17.0
    - opentelemetry-sdk>=1.17.0