version: '3.8'

services:
  audio-processing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-gen-audio-processing
    ports:
      - "8002:8002"
    environment:
      - STORAGE_PATH=/app/storage
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - SERVICE_API_KEY=${SERVICE_API_KEY:-internal-service-key-change-in-production}
      - USE_S3=${USE_S3:-false}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-music-gen-audio}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
    volumes:
      - ./storage:/app/storage
      - ./temp:/tmp/audio_processing
    restart: unless-stopped
    networks:
      - music-gen-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Optional MinIO for local S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: music-gen-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - music-gen-network
    restart: unless-stopped

volumes:
  minio_data:
    driver: local

networks:
  music-gen-network:
    driver: bridge