# High quality inference configuration

# Generation parameters
max_length: 2048  # Longer sequences
temperature: 0.7  # More conservative
top_k: 30
top_p: 0.85
do_sample: false
repetition_penalty: 1.15

# Beam search parameters for quality
num_beams: 8  # More beams for better quality
length_penalty: 1.2
diversity_penalty: 0.3
early_stopping: true
no_repeat_ngram_size: 4

# Audio generation
default_duration: 15.0  # Longer default
max_duration: 120.0
min_duration: 2.0

# Quality settings
use_cache: true
compile_model: false