version: '3.8'

services:
  musicgen-api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MUSICGEN_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - PROMETHEUS_PORT=9090
    depends_on:
      - redis
      - prometheus
    volumes:
      - ./configs:/app/configs:ro
      - musicgen-models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  musicgen-worker:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.worker
    environment:
      - MUSICGEN_ENV=production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./configs:/app/configs:ro
      - musicgen-models:/app/models
    restart: unless-stopped
    deploy:
      replicas: 2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  musicgen-models:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  default:
    name: musicgen-network