version: '3.8'

services:
  generation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-gen-generation-service
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - STORAGE_PATH=/app/storage
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - SERVICE_API_KEY=${SERVICE_API_KEY:-internal-service-key-change-in-production}
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
      - TORCH_HOME=/app/cache
      - PYTHONPATH=/app
    volumes:
      - ./storage:/app/storage
      - model_cache:/app/cache
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - music-gen-network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:7-alpine
    container_name: music-gen-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - music-gen-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  model_cache:
    driver: local
  redis_data:
    driver: local

networks:
  music-gen-network:
    driver: bridge