# API Gateway Service Kubernetes Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: musicgen-prod
  labels:
    app: musicgen-ai
    service: gateway
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: musicgen-ai
      service: gateway
  template:
    metadata:
      labels:
        app: musicgen-ai
        service: gateway
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: gateway
        image: musicgen-ai/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: GENERATION_SERVICE_URL
          value: "http://generation-service:8001"
        - name: MODEL_SERVICE_URL
          value: "http://model-service:8002"
        - name: PROCESSING_SERVICE_URL
          value: "http://processing-service:8003"
        - name: STORAGE_SERVICE_URL
          value: "http://storage-service:8004"
        - name: USER_MGMT_SERVICE_URL
          value: "http://user-management-service:8005"
        - name: ANALYTICS_SERVICE_URL
          value: "http://analytics-service:8006"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: musicgen-secrets
              key: jwt-secret
        - name: GATEWAY_WORKERS
          value: "4"
        - name: RATE_LIMIT_RPM
          value: "100"
        - name: RATE_LIMIT_RPH
          value: "1000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: musicgen-prod
  labels:
    app: musicgen-ai
    service: gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app: musicgen-ai
    service: gateway

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: musicgen-prod
  labels:
    app: musicgen-ai
    service: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: musicgen-prod
  labels:
    app: musicgen-ai
    service: gateway
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: musicgen-ai
      service: gateway

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-network-policy
  namespace: musicgen-prod
  labels:
    app: musicgen-ai
    service: gateway
spec:
  podSelector:
    matchLabels:
      app: musicgen-ai
      service: gateway
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: musicgen-ai
    ports:
    - protocol: TCP
      port: 8001
    - protocol: TCP
      port: 8002
    - protocol: TCP
      port: 8003
    - protocol: TCP
      port: 8004
    - protocol: TCP
      port: 8005
    - protocol: TCP
      port: 8006
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53